---
title: "Assignment 1.2R"
subtitle: '2022 Programming in Psychological Science'
output:
  pdf_document:
    toc: yes
  html_document:
    toc: yes
---

<!-- Authors: Michael D. Nunez, Hannes Rosenbusch-->

<!-- Changes: -->
<!-- Michael 7-Jan-21 -->

### Assignment description

Work through the following R challenge problem. This problem is worth 2 points if completely correct. You should also complete Assignment 1.1 for 8 points. The total of Assignments 1.1 and your choice of either 1.2R (this R challenge) or 1.2P (Python) are worth 10 points and 15% of your final course grade. You must work individually, but feel free to ask questions in class and on Slack! 

You must submit the solution as an R script (.R file). Note that all comments have `#` in front of them so that R does not run this line of code.



### Challenge problem

## Q1.2R.1

Build a script that simulates a multivariate normal distribution without using any libraries besides base R. For instance, you are not allowed to use the mvrnorm function. 

Then, compare the speed of your script to the MASS::mvrnorm function using only base R functions besides mvrnorm().

Use matrix multiplication in R. You can write a script by setting a vector `Mu` and matrix `Sigma` to certain values at the beginning of your script. You do not have to write an R function, which we learn more about next week. You should also avoid using loops, which we will also learn about next week. 

Hint: ?chol
